language: python


services:
  - docker

env:
  global:
    - IMAGE=mlfmonde/cluster_cli
    - TAG=latest

python:
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"


matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"


install:
  - pip install -r requirements.tests.txt
  - python setup.py develop
  - pip install coveralls

script:
  - py.test --cov=cluster -v --pep8

after_success:
  coveralls

jobs:
  include:
    - name: publish-docker-image
      if: branch = master AND type != pull_request
      script:
        - docker build -t $IMAGE:$TAG .
        - docker run --rm $IMAGE:$TAG
        - echo "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USERNAME --password-stdin && docker push $IMAGE:$TAG
