language: python


python:
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"


matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"


install:
  - pip install -r requirements.tests.txt
  - python setup.py develop
  - pip install coveralls

script:
  - py.test --cov=cluster -v --pep8

after_success:
  coveralls
