language: python

sudo: required

services:
  - docker

env:
  global:
    - IMAGE=mlfmonde/cluster_cli
    - TAG=latest

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "nightly"


matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"


install:
  - pip install -r requirements.tests.txt
  - python setup.py develop
  - pip install coveralls
  - docker build -t $IMAGE:$TAG .

script:
  - py.test --cov=cluster -v --pep8
  - docker run --rm $IMAGE:$TAG
  - coveralls

after_success:
  if: branch = master AND type = pull_request AND env(TRAVIS_PYTHON_VERSION) = 3.7
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u $DOCKER_HUB_USERNAME --password-stdin && docker push $IMAGE:$TAG
